language: cpp

services:
  - docker

jobs:
  include:
    - stage: 'Update Version'
      script:
        - cd ci-scripts
        - npm install
        - ./AutoUpdate.sh

    - stage: 'Build'
      before_install:
        - docker pull trzeci/emscripten:1.39.10-upstream
      script:
        - docker run --name dxlib --volume ${TRAVIS_BUILD_DIR}:/src trzeci/emscripten:1.39.10-upstream bash -c "mkdir build && cd build && emcmake cmake .. && emmake make"
        - mkdir dest
        - mkdir dest/bin
        - cp build/libDxLib.a dest/bin/
        - cp build/libDxUseCLib.a dest/bin/
        - cp build/libDxDrawFunc.a dest/bin/
        - mkdir dest/include
        - cp DxCompileConfig.h dest/include/
        - cp DxDataType.h dest/include/
        - cp DxDataTypeHTML5.h dest/include/
        - cp DxFunctionWin.h dest/include/
        - cp DxLib.h dest/include/
        - zip -r DxLibForHTML5.zip dest
        - tar -cvzf DxLibForHTML5.tgz dest/*

    - stage: 'Deploy'
      script: skip
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        file:
          - DxLibForHTML5.zip
          - DxLibForHTML5.tgz
        skip_cleanup: true
        on:
          tags: true

stages:
  - name: 'Update Version'
    if: type = cron
  - name: 'Build'
  - name: 'Deploy'
