// -------------------------------------------------------------------------------
// 
// 		ＤＸライブラリ		HTML5用入力情報プログラムヘッダファイル
// 
// 				Ver 3.21f
// 
// -------------------------------------------------------------------------------

#ifndef DX_INPUT_KEYCODES_HTML5_H
#define DX_INPUT_KEYCODES_HTML5_H

#define HTML_KEYCODE_BACK (0x2E)
#define HTML_KEYCODE_TAB (0x09)
#define HTML_KEYCODE_RETURN (0x0D)

#define HTML_KEYCODE_LSHIFT (0x10)
#define HTML_KEYCODE_RSHIFT (0x10)
#define HTML_KEYCODE_LCONTROL (0x11)
#define HTML_KEYCODE_RCONTROL (0x11)
#define HTML_KEYCODE_ESCAPE (0x1B)
#define HTML_KEYCODE_SPACE (0x20)
#define HTML_KEYCODE_PGUP (0x21)
#define HTML_KEYCODE_PGDN (0x22)
#define HTML_KEYCODE_END (0x23)
#define HTML_KEYCODE_HOME (0x24)
#define HTML_KEYCODE_LEFT (0x25)
#define HTML_KEYCODE_UP (0x26)
#define HTML_KEYCODE_RIGHT (0x27)
#define HTML_KEYCODE_DOWN (0x28)
#define HTML_KEYCODE_INSERT (0x2D)
#define HTML_KEYCODE_DELETE (0x2E)

#define HTML_KEYCODE_MINUS (0xBD)

#define HTML_KEYCODE_YEN (0xDC)
#define HTML_KEYCODE_PREVTRACK (0xDE)
#define HTML_KEYCODE_PERIOD (0xBE)
#define HTML_KEYCODE_SLASH (0xBF)
#define HTML_KEYCODE_LALT (0x12)
#define HTML_KEYCODE_RALT (0x12)
#define HTML_KEYCODE_SCROLL (0x91)
#define HTML_KEYCODE_SEMICOLON (0xBB)
#define HTML_KEYCODE_COLON (0xBA)
#define HTML_KEYCODE_LBRACKET (0xDB)
#define HTML_KEYCODE_RBRACKET (0xDD)
#define HTML_KEYCODE_AT (0xDB)
#define HTML_KEYCODE_BACKSLASH (0xDD)
#define HTML_KEYCODE_COMMA (0xBC)
// #define HTML_KEYCODE_KANJI
// #define HTML_KEYCODE_CONVERT
// #define HTML_KEYCODE_NOCONVERT
// #define HTML_KEYCODE_KANA
// #define HTML_KEYCODE_APPS
#define HTML_KEYCODE_CAPSLOCK (0x14)
// #define HTML_KEYCODE_SYSRQ
#define HTML_KEYCODE_PAUSE (0x13)
#define HTML_KEYCODE_LWIN (0x5B)
#define HTML_KEYCODE_RWIN (0x5C)

#define HTML_KEYCODE_NUMLOCK (0x90)
#define HTML_KEYCODE_NUMPAD0 (0x60)
#define HTML_KEYCODE_NUMPAD1 (0x61)
#define HTML_KEYCODE_NUMPAD2 (0x62)
#define HTML_KEYCODE_NUMPAD3 (0x63)
#define HTML_KEYCODE_NUMPAD4 (0x64)
#define HTML_KEYCODE_NUMPAD5 (0x65)
#define HTML_KEYCODE_NUMPAD6 (0x66)
#define HTML_KEYCODE_NUMPAD7 (0x67)
#define HTML_KEYCODE_NUMPAD8 (0x68)
#define HTML_KEYCODE_NUMPAD9 (0x69)
#define HTML_KEYCODE_MULTIPLY (0x6A)
#define HTML_KEYCODE_ADD (0x6B)
#define HTML_KEYCODE_SUBTRACT (0x6D)
#define HTML_KEYCODE_DECIMAL (0x6E)
#define HTML_KEYCODE_DIVIDE (0x6F)
#define HTML_KEYCODE_NUMPADENTER (0x0D)

#define HTML_KEYCODE_F1 (0x70)
#define HTML_KEYCODE_F2 (0x71)
#define HTML_KEYCODE_F3 (0x72)
#define HTML_KEYCODE_F4 (0x73)
#define HTML_KEYCODE_F5 (0x74)
#define HTML_KEYCODE_F6 (0x75)
#define HTML_KEYCODE_F7 (0x76)
#define HTML_KEYCODE_F8 (0x77)
#define HTML_KEYCODE_F9 (0x78)
#define HTML_KEYCODE_F10 (0x79)
#define HTML_KEYCODE_F11 (0x7A)
#define HTML_KEYCODE_F12 (0x7B)

#define HTML_KEYCODE_A (0x41)
#define HTML_KEYCODE_B (0x42)
#define HTML_KEYCODE_C (0x43)
#define HTML_KEYCODE_D (0x44)
#define HTML_KEYCODE_E (0x45)
#define HTML_KEYCODE_F (0x46)
#define HTML_KEYCODE_G (0x47)
#define HTML_KEYCODE_H (0x48)
#define HTML_KEYCODE_I (0x49)
#define HTML_KEYCODE_J (0x4A)
#define HTML_KEYCODE_K (0x4B)
#define HTML_KEYCODE_L (0x4C)
#define HTML_KEYCODE_M (0x4D)
#define HTML_KEYCODE_N (0x4E)
#define HTML_KEYCODE_O (0x4F)
#define HTML_KEYCODE_P (0x50)
#define HTML_KEYCODE_Q (0x51)
#define HTML_KEYCODE_R (0x52)
#define HTML_KEYCODE_S (0x53)
#define HTML_KEYCODE_T (0x54)
#define HTML_KEYCODE_U (0x55)
#define HTML_KEYCODE_V (0x56)
#define HTML_KEYCODE_W (0x57)
#define HTML_KEYCODE_X (0x58)
#define HTML_KEYCODE_Y (0x59)
#define HTML_KEYCODE_Z (0x5A)

#define HTML_KEYCODE_0 (0x30)
#define HTML_KEYCODE_1 (0x31)
#define HTML_KEYCODE_2 (0x32)
#define HTML_KEYCODE_3 (0x33)
#define HTML_KEYCODE_4 (0x34)
#define HTML_KEYCODE_5 (0x35)
#define HTML_KEYCODE_6 (0x36)
#define HTML_KEYCODE_7 (0x37)
#define HTML_KEYCODE_8 (0x38)
#define HTML_KEYCODE_9 (0x39)

#endif // DX_INPUT_KEYCODES_HTML5_H