name: C/C++ Update

on:
  workflow_dispatch:
  push:
    branch: [ develop ]
    paths:
      - '.github/workflows/cron.yml'
  schedule:
    - cron: '0 15 * * 0'

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true 
      - env: 
          LANG: C.UTF-8
        run: |
          cp -r ci-scripts ci-scripts-temp
          cd ci-scripts-temp
          node --version
          npm install
          bash ./AutoUpdate.sh
